### ISSUE TITLE
ImportError: libnccl.so.2: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by FOSSEnjoyer69** [pinokiocomputer/pinokio#193]
'libnccl.so.2' which is a dependency that most of the scripts i have tried is not installed when Pinokio first launches

this is the error i get when trying to start 'StableDiffusion Comics'

<<PINOKIO SHELL>>eval "$(conda shell.bash hook)" && conda deactivate && conda deactivate && conda deactivate && conda activate base && source /home/usr/pinokio/api/storydiffusion-comics.git/app/env/bin/activate /home/usr/pinokio/api/storydiffusion-comics.git/app/env && python app.py

Traceback (most recent call last):
  File "/home/usr/pinokio/api/storydiffusion-comics.git/app/app.py", line 6, in <module>
    import torch
  File "/home/usr/pinokio/api/storydiffusion-comics.git/app/env/lib/python3.10/site-packages/torch/__init__.py", line 290, in <module>
    from torch._C import *  # noqa: F403
ImportError: libnccl.so.2: cannot open shared object file: No such file or directory
(env) (base) <<PINOKIO SHELL>>

**Comment by FOSSEnjoyer69** [comment]
this is how to fix it using the terminal on Ubuntu, it should still be installed when Pinokio first launches tho.

sudo apt update && sudo apt upgrade

sudo apt install build-essential dkms

wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-keyring_1.0-1_all.deb
sudo dpkg -i cuda-keyring_1.0-1_all.deb
sudo apt-get update

sudo apt install libnccl2 libnccl-dev

ldconfig -p | grep libnccl

**Comment by vuklazovic** [comment]
@FOSSEnjoyer69  Thanks !

**Comment by alita-moore** [comment]
what's a version for debian12?

**Comment by SuperUserNameMan** [comment]
Several other linux distro and version available :
https://developer.download.nvidia.com/compute/cuda/repos/

**Comment by behroozazarkhalili** [comment]
> this is how to fix it using the terminal on Ubuntu, it should still be installed when Pinokio first launches tho.
> 
> sudo apt update && sudo apt upgrade
> 
> sudo apt install build-essential dkms
> 
> wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-keyring_1.0-1_all.deb sudo dpkg -i cuda-keyring_1.0-1_all.deb sudo apt-get update
> 
> sudo apt install libnccl2 libnccl-dev
> 
> ldconfig -p | grep libnccl

It works perfectly. Thank you.

**Comment by evandrouzeda** [comment]
I have a dirty hands soluciotion:

In my case, using Manjaro Linux, I need to Download the tar file package from [NVIDIA](https://developer.nvidia.com/nccl) using this [Install Guide](https://docs.nvidia.com/deeplearning/nccl/install-guide/index.html#tar).

After extract I need to copy the content in `nccl-version/lib/` to the torch lib folder.

Copy the content from here
```
/home/myuser/Downloads/nccl_2.23.4-1+cuda12.6_x86_64/lib/
```
to
```
/home/myuser/pinokio/api/fish.git/app/env/lib/python3.10/site-packages/torch/lib/
```

I hope this helps someone not using Ubuntu

**Comment by giswqs** [comment]
I just run into the same issue on Manjaro Linux. After running `sudo pacman -S nccl`, the problem got resolved.

**Comment by KQDtianxiaK** [comment]
> I have a dirty hands soluciotion:
> 
> In my case, using Manjaro Linux, I need to Download the tar file package from [NVIDIA](https://developer.nvidia.com/nccl) using this [Install Guide](https://docs.nvidia.com/deeplearning/nccl/install-guide/index.html#tar).
> 
> After extract I need to copy the content in `nccl-version/lib/` to the torch lib folder.提取后，我需要将 `nccl-version/lib/` 中的内容复制到 torch lib 文件夹中。
> 
> Copy the content from here
> 
> ```
> /home/myuser/Downloads/nccl_2.23.4-1+cuda12.6_x86_64/lib/
> ```
> 
> to
> 
> ```
> /home/myuser/pinokio/api/fish.git/app/env/lib/python3.10/site-packages/torch/lib/
> ```
> 
> I hope this helps someone not using Ubuntu

Thank you so much! You are my Superman.
