### ISSUE TITLE
Fresh install of ComfyUI fails at step 8

### ISSUE THREAD

**Issue by cmackenna** [pinokiocomputer/pinokio#194]
(upgraded to Pinokio-2.1.14 from Pinokio-1.3.4)

Fresh install of ComfyUI fails at step 8
workaround required manual download of file 'sd_xl_base_1.0.safetensors'

manually downloaded file:
https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/resolve/main/sd_xl_base_1.0.safetensors

put file here:
\pinokio\api\comfyui.git\app\models\checkpoints

ComfyUI "Reinstall" then moves on to step 9 and completes install

however ComfyUI "Start" gives the following error:
AssertionError: Torch not compiled with CUDA enabled

no problems with other pinokio computer APPs:
aitown.git
chatbot-ollama.git
ExVideo-SVD-128f-v1
gepeto.git
hallo.git
InstantVIdeo
liveportrait.git
MagicAnimateMini.git
Midjourney
openvoice2.git
stableaudio.git
streamdiffusion.git
vid2pose.git

Win 11 workstation:
AMD Ryzen 9 5900X 64 GB
NVIDIA GeForce RTX 3090 24GB

. . .

Microsoft Windows [Version 10.0.22631.3880]
(c) Microsoft Corporation. All rights reserved.

C:\pinokio\api\comfyui.git\app>conda_hook && conda deactivate && conda deactivate && conda deactivate && conda activate base && C:\pinokio\api\comfyui.git\app\env\Scripts\activate C:\pinokio\api\comfyui.git\app\env && python main.py --disable-xformers
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-07-27 03:51:44.931380
** Platform: Windows
** Python version: 3.10.14 | packaged by conda-forge | (main, Mar 20 2024, 12:40:08) [MSC v.1938 64 bit (AMD64)]
** Python executable: C:\pinokio\api\comfyui.git\app\env\Scripts\python.exe
** ComfyUI Path: C:\pinokio\api\comfyui.git\app
** Log path: C:\pinokio\api\comfyui.git\app\comfyui.log

Prestartup times for custom nodes:
   1.2 seconds: C:\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI-Manager

Traceback (most recent call last):
  File "C:\pinokio\api\comfyui.git\app\main.py", line 86, in <module>
    import execution
  File "C:\pinokio\api\comfyui.git\app\execution.py", line 12, in <module>
    import nodes
  File "C:\pinokio\api\comfyui.git\app\nodes.py", line 21, in <module>
    import comfy.diffusers_load
  File "C:\pinokio\api\comfyui.git\app\comfy\diffusers_load.py", line 3, in <module>
    import comfy.sd
  File "C:\pinokio\api\comfyui.git\app\comfy\sd.py", line 5, in <module>
    from comfy import model_management
  File "C:\pinokio\api\comfyui.git\app\comfy\model_management.py", line 119, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
  File "C:\pinokio\api\comfyui.git\app\comfy\model_management.py", line 88, in get_torch_device
    return torch.device(torch.cuda.current_device())
  File "C:\pinokio\api\comfyui.git\app\env\lib\site-packages\torch\cuda\__init__.py", line 878, in current_device
    _lazy_init()
  File "C:\pinokio\api\comfyui.git\app\env\lib\site-packages\torch\cuda\__init__.py", line 305, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

**Comment by cmackenna** [comment]
issue resolved by installing community script 'comfyui.pinokio.git' instead of using official script 'comfyui.git'

**Comment by cmackenna** [comment]
I see the ComfyUI official installer has been updated and corrects this issue.  That's great, and important I think because ComfyUI is popular.
