### ISSUE TITLE
Installing Story Diffusion Comics App with Pinokio 2.15.1 in Ubuntu 22.04 Jammy OS fails/w missing libnccl.so.2 error.

### ISSUE THREAD

**Issue by mbennette68** [pinokiocomputer/pinokio#230]
In Ubuntu 22.04 Jammy based OS, using **_Pinokio 2.15.1_**, I tried to install, **_StoryDiffusion Comics_** but got the below error which seems to suggest that **_libnccl.so.2_** is either not installed or not in Pinokio's path:

```
_Traceback most recent call last):
  File "/home/username/pinokio/api/storydiffusion-comics/app/env/lib/python3.10/site-packages/torch/__init__.py", line 290, in <module>
    from torch._C import *  # noqa: F403_
_ImportError: libnccl.so.2: cannot open shared object file: No such file or directory_
```

**SPECS:**
**Laptop**: 16GB RAM, Intel® Core™ i7-10750H CPU
**OS**:         Ubuntu 22.04 LTS 64bit
**VID**:        Nvidia RTX2060 video card

Everything gets installed but then the error gets spit out and then it stops.

**Comment by joesponde** [comment]
Same error here.

**Comment by icemanus** [comment]
for the same problem chatgpt gave me this solution : add the path of required file to the start.js . That worked for me.

 env: { 
          LD_LIBRARY_PATH: "/home/username/pinokio/api/yourapp.git/app/env/lib64/python3.10/site-packages/nvidia/cudnn/lib:$LD_LIBRARY_PATH"
        },

**Comment by mbennette68** [comment]
Hello,

I followed the, below, steps and that seems to have worked after the initial download then execution, for the most part.

> for the same problem chatgpt gave me this solution : add the path of required file to the start.js . That worked for me.
> 
> env: { LD_LIBRARY_PATH: "/home/username/pinokio/api/yourapp.git/app/env/lib64/python3.10/site-packages/nvidia/cudnn/lib:$LD_LIBRARY_PATH" }, you can change "cudnn" with "nccl."

The only change I had to make was replace "**_cudnn_**" with "**_nccl_**" which doesn't  make sense since I'm just testing this on an Nvidia Laptop with one GPU. Either way, it seems to have worked up to a certain point, the *.safetensor files were downloaded which totaled over 15GB of space, not counting **_miniconda_**. In any case, the load was too much even for my machine which froze 😒. I decided to just remove the app and will probably remove Pinokio as it appears to be designed for more powerful hardware than I have. I'm also running everything on half a terabyte drive, thus space quickly becomes an issue.

Thank you for the assist, 
MB

**Comment by icemanus** [comment]
> Hello,
> 
> I followed the, below, steps and that seems to have worked after the initial download then execution, for the most part.
> 
> > for the same problem chatgpt gave me this solution : add the path of required file to the start.js . That worked for me.
> > env: { LD_LIBRARY_PATH: "/home/username/pinokio/api/yourapp.git/app/env/lib64/python3.10/site-packages/nvidia/cudnn/lib:$LD_LIBRARY_PATH" }, you can change "cudnn" with "nccl."
> 
> The only change I had to make was replace "**_cudnn_**" with "**_nccl_**" which doesn't make sense since I'm just testing this on an Nvidia Laptop with one GPU. Either way, it seems to have worked up to a certain point, the *.safetensor files were downloaded which totaled over 15GB of space, not counting **_miniconda_**. In any case, the load was too much even for my machine which froze 😒. I decided to just remove the app and will probably remove Pinokio as it appears to be designed for more powerful hardware than I have. I'm also running everything on half a terabyte drive, thus space quickly becomes an issue.
> 
> Thank you for the assist, MB

it is good to hear my suggestion has worked. Most of video based applications need powerful configuration unfortunately

**Comment by paboum** [comment]
Related: https://github.com/pinokiocomputer/pinokio/issues/931
